# Generated by Django 2.0.1 on 2018-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointApp', '0003_auto_20180122_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT'), ('RECEPTIONIST', 'RECEPTIONIST')], max_length=15, null=True),
        ),
    ]
